#!/usr/bin/env python3

import threading
import time

"""
Module Docstring
"""
ENGINE_REDLINE = 15,000

ECU_CAR_CLOCK = time.perf_counter()
ECU_ENGINE_SPEED = 3500 
ECU_CAR_SPEED = 0
ECU_CAR_GEAR = 0
ECU_CAR_THROTTLE = 1
ECU_CAR_BRAKE = 0


__author__ = "Ethan"
__license__ = "MIT"

def updateECU():
    while True:
        print ("Clock: " , ECU_CAR_CLOCK)
        print ("Engine Speed: " , ECU_ENGINE_SPEED)
        print ("Car Speed: " , ECU_CAR_SPEED)
        print ("Gear: " , ECU_CAR_GEAR)
        print ("Throttle: " , ECU_CAR_THROTTLE)
        print ("Brake: " , ECU_CAR_BRAKE)
        time.sleep(0.03)

def simulateCar():
    while True:
        global ECU_CAR_CLOCK
        global ECU_ENGINE_SPEED
        
        oldTime = ECU_CAR_CLOCK 
        ECU_CAR_CLOCK = time.perf_counter()

        timeDiff = ECU_CAR_CLOCK - oldTime
        if (ECU_ENGINE_SPEED <= 15000):
            ECU_ENGINE_SPEED = ECU_ENGINE_SPEED + ((1000 * (timeDiff * ECU_CAR_THROTTLE)) ** 2) 

        time.sleep(0.03)


def main():
    """ Main entry point of the app """
    print_thread = threading.Thread(target=updateECU)
    print_thread_daemon = True

    carsim_thread = threading.Thread(target=simulateCar)
    print_thread_daemon = True

    carsim_thread.start()

    print_thread.start()



if __name__ == "__main__":
    """ This is executed when run from the command line """
    main()


